{% set name = "tomli" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tomli-{{ version }}.tar.gz
  sha256: d46d457a85337051c36524bc5349dd91b1877838e2979ac5ced3e710ed8a60ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    # Cannot use flit-core >3.3.0 due to cyclic dependency
    - flit-core 3.3.0
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - tomli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hukkin/tomli
  summary: A simple TOML parser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
