# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.5.0"
  python_check_max: "3.14"

package:
  name: tomli
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tomli/tomli-${{ version }}.tar.gz
  sha256: 264507556cd8b8c8e7c6ee037cdf443a463f03f4c958e57195e3d369711b8ff6

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies

requirements:
  host:
    - flit-core >=3.12,<5
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - package_contents:
      strict: true
      site_packages:
        - tomli/**
        - tomli-${{ version }}.dist-info/**
  - python:
      imports: tomli
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

about:
  summary: A simple TOML parser
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/tomli
  repository: https://github.com/hukkin/tomli

extra:
  recipe-maintainers:
    - thewchan
    - bollwyvl
